apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-10535993-api-staging
spec:
  selector:
    matchLabels:
      deployment-name: pf-10535993-api-staging
  replicas: 1
  template:
    metadata:
      labels:
        deployment-name: pf-10535993-api-staging
    spec:
      containers:
        - name: pf-10535993-api-staging
          image: b8it131registry.azurecr.io/pf-10535993-api-staging:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: pf-10535993-api-loadbalancer-service-staging
  name: pf-10535993-api-loadbalancer-service-staging
spec:
  type: LoadBalancer
  ports:
    - name: pf-10535993-api-loadbalancer-service-port-staging
      port: 3000
      protocol: TCP
  selector:
    deployment-name: pf-10535993-api-loadbalancer-staging