apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-mongo-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: pf-mongo-staging
  template:
    metadata:
      labels:
        deployment-name: pf-mongo-staging
    spec:
      containers:
        - name: pf-mongo-container-staging
          image: mongo
          env: 
            - name: MONGO_10535993_INITDB_DB
              value: database
          ports:
            - containerPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: pf-mongo-loadbalancer-staging
  name: pf-mongo-loadbalancer-staging
spec:
  type: LoadBalancer
  ports:
    - name: pf-mongo-loadbalancer-service-port-staging
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    deployment-name: pf-mongo-loadbalancer-staging