apiVersion: apps/v1

kind: Deployment

metadata:
  name: api-10535993-deployment
  
spec:
  selector:
    matchLabels:
      deployment-name: api-10535993-pod
  replicas: 2
  template:
    metadata:
      labels:
        deployment-name: api-10535993-pod
    spec:
      containers:
        - name: api-10535993-container
          image: api-10535993-image:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1

kind: Service

metadata:
  labels:
    service-label: api-10535993-loadbalancer-service
  name: api-10535993-service

spec:
  type: LoadBalancer
  ports:
  - name: api-10535993-loadbalancer-service-port
    port: 3000
    protocol: TCP
  selector:
    deployment-name: api-10535993-pod
---
apiVersion: v1

kind: Service

metadata:
  labels:
    service-label: api-10535993-cluster-service
  name: api-10535993-cluster-service

spec:
  type: ClusterIP
  ports:
  - name: api-10535993-cluster-service-port
    port: 80
    protocol: TCP
  selector:
    deployment-name: api-10535993-pod

