apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-api-prod
spec:
  selector:
    matchLabels:
      deployment-name: pf-api-prod
  replicas: 1
  template:
    metadata:
      labels:
        deployment-name: pf-api-prod
    spec:
      containers:
        - name: pf-api-prod
          image: b8it131reg2.azurecr.io/pf-api-prod:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: pf-api-loadbalancer-service-prod
  name: pf-api-loadbalancer-service-prod
spec:
  type: LoadBalancer
  ports:
    - name: pf-api-loadbalancer-service-port-prod
      port: 3000
      protocol: TCP
  selector:
    deployment-name: pf-api-loadbalancer-prod
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pf-api-prod-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pf-api-prod
  targetCPUUtilizationPercentage: 60
